Feature/3642 remove references of js templates
brightlayer-ui/doc-it pull request #608
Opened 2022-12-14 12:09 UTC by bkarambe

Fixes # BLUI-3642

#### Changes proposed in this Pull Request:
- Removed react and react native js template references

#### Screenshots:

#### To Test:
- yarn start

2022-12-14 16:57 UTC, daileytj requested changes
I would undo all of the changes in the src/docs/migration.mdx file as that should live as a historical record of the migration instructions from pxblue to BLUI. It doesn't look like we actually use that doc any longer so we may want to just remove it in the future. For now I would leave it as it was.

I only looked at the code changes soo far. I'll need to dig into the source code to see if there are any lingering mentions of these resources.

2022-12-14 16:57 UTC, daileytj commented on src/docs/development/frameworks-web/react.mdx
> +You will be asked to provide a name for your project, you'll be asked if you want to use the Brightlayer UI eslint and prettier configurations files.
```suggestion
You will be asked to provide a name for your project and whether you want to use the Brightlayer UI eslint and prettier configuration files.
```

2022-12-14 17:34 UTC, daileytj commented
- [ ] The [developer section of visualizations design patterns](https://blui-doc-it--pr608-feature-3642-remove-ycxcv4y7.web.app/patterns/visualizations#developers) should no longer reference high charts, chart js, and mapbox. 
- [ ] @joebochill should we drop support for victory native as well? (I'm not even sure which resources we have to support that). If so, remove that as well.
- [ ] In place of the items removed, add a blurb about DDS and links to their site and storybook (I'll add them here when I confirm what they are)
- [ ] Update the "Can I use other charting solutions..." answer on the [FAQ page](https://blui-doc-it--pr608-feature-3642-remove-ycxcv4y7.web.app/community/faq)

2022-12-15 09:03 UTC, bkarambe commented
> * [x]  The [developer section of visualizations design patterns](https://blui-doc-it--pr608-feature-3642-remove-ycxcv4y7.web.app/patterns/visualizations#developers) should no longer reference high charts, chart js, and mapbox.
> * [ ]  @joebochill should we drop support for victory native as well? (I'm not even sure which resources we have to support that). If so, remove that as well.
> * [ ]  In place of the items removed, add a blurb about DDS and links to their site and storybook (I'll add them here when I confirm what they are)
> * [ ]  Update the "Can I use other charting solutions..." answer on the [FAQ page](https://blui-doc-it--pr608-feature-3642-remove-ycxcv4y7.web.app/community/faq)

In the answer of that FAQ, we are recommending chartjs and highcharts libraries. Those are not blui libraries. Don't we want to recommend those?

2022-12-15 11:52 UTC, joebochill commented
Friendly reminder to target the `feature/mui5-migration` branch to make @daileytj's life easier when he picks up that story. Otherwise he's going to have to redo all of these changes.

2022-12-15 11:53 UTC, joebochill commented
Please update the PR title since this has nothing to do with JS CLI templates

2022-12-15 12:00 UTC, joebochill commented on src/docs/patterns/visualizations.mdx
> +-   Brightlayer Charts
Combine all of this into one line like:

'- [Brightlayer Charts](link to docs) ([Storybook](link to storybook))'

2022-12-15 12:00 UTC, joebochill commented on src/docs/patterns/visualizations.mdx
> +-   Brightlayer Charts
This section isn't really about explaining what these recommendations are, just linking to them. We will revamp this entire page in a future story to better steer users in that direction. For now we're just trying to remove references to deprecated stuff.

2022-12-15 12:01 UTC, joebochill commented
As for victory native, we should leave that for now. We don't have any official resources related to it, it's just a recommendation. And DDS doesn't have a solution for RN that would replace it.

2022-12-15 12:17 UTC, joebochill commented
Do you also want to include changes to address the icon repository restructuring in this PR too, or save that for a separate one?

2022-12-19 09:58 UTC, bkarambe commented
> Do you also want to include changes to address the icon repository restructuring in this PR too, or save that for a separate one?

It would be better if we save it for later

2022-12-19 10:05 UTC, bkarambe commented
Raised another PR against mui migration branch. https://github.com/brightlayer-ui/doc-it/pull/610

2022-12-19 10:05 UTC, closed without merging